from ai.tool_registry import TOOLS


def execute_plan(plan, image_paths):

    # Files currently being processed
    current_files = list(image_paths)

    # Every file generated by the agent
    all_generated_files = []

    for step in plan:

        tool_name = step.get("tool")

        # ==========================================
        # CONVERT
        # ==========================================

        if tool_name == "convert":

            output_format = step.get(
                "format",
                "jpg"
            )

            converted_files = []

            for image_path in current_files:

                output_path = TOOLS["convert"](
                    image_path,
                    output_format
                )

                converted_files.append(
                    output_path
                )

                all_generated_files.append(
                    output_path
                )

            current_files = converted_files

        # ==========================================
        # COMPRESS
        # ==========================================

        elif tool_name == "compress":

            target_size = step.get(
                "target",
                "500kb"
            )

            target_map = {
                "100kb": 100,
                "200kb": 200,
                "500kb": 500,
                "1mb": 1024
            }

            target_size_kb = target_map.get(
                target_size.lower(),
                500
            )

            compressed_files = []

            for image_path in current_files:

                output_path = TOOLS["compress"](
                    image_path,
                    target_size_kb
                )

                compressed_files.append(
                    output_path
                )

                all_generated_files.append(
                    output_path
                )

            current_files = compressed_files

        # ==========================================
        # PDF
        # ==========================================

        elif tool_name == "pdf":

            # PDF must be created from the
            # CURRENT processed images.
            pdf_path = TOOLS["pdf"](
                current_files
            )

            # Keep PDF as an additional result.
            all_generated_files.append(
                pdf_path
            )

            # Do NOT replace current_files.
            #
            # This means if the user asked:
            #
            # Convert → WebP
            # Create PDF
            #
            # we keep:
            #
            # image1.webp
            # image2.webp
            # image3.webp
            #
            # and additionally:
            #
            # generated.pdf

        # ==========================================
        # UNKNOWN TOOL
        # ==========================================

        else:

            # Ignore unknown planner steps
            # instead of crashing the whole agent.
            continue

    return all_generated_files